In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from tqdm.notebook import tqdm
from joblib import dump, load

In [2]:
mlp_classifier = load('/storage/ice1/1/7/khayashi31/Hacklytics/Model/trained_mlp_model.joblib')

In [3]:
mlp_classifier

MLPClassifier(learning_rate='adaptive', verbose=True)

In [4]:
test_data = pd.read_csv('/storage/ice1/1/7/khayashi31/Hacklytics/feature_engineering_data.csv', skiprows=range(1, int(.98*34085)))

In [7]:
y = test_data['label']
X = test_data.drop(columns=['Unnamed: 0', 'Brief Summary', 'Conditions', 'Interventions', 'Primary Outcome Measures', 'Secondary Outcome Measures',
                'Other Outcome Measures', 'Sponsor', 'Collaborators', 'Sex', 'Age', 'Phases', 'Enrollment', 'Funder Type', 'Study Type', 'Study Design', 'label', 'Allocation', 'Intervention Model', 'Masking', 'Primary Purpose'] )

In [10]:
X

,female,male,Funder_Type_FED,Funder_Type_INDIV,Funder_Type_INDUSTRY,Funder_Type_NETWORK,Funder_Type_NIH,Funder_Type_OTHER,Funder_Type_OTHER_GOV,Funder_Type_UNKNOWN,...,other_outcome_measures_vector_374,other_outcome_measures_vector_375,other_outcome_measures_vector_376,other_outcome_measures_vector_377,other_outcome_measures_vector_378,other_outcome_measures_vector_379,other_outcome_measures_vector_380,other_outcome_measures_vector_381,other_outcome_measures_vector_382,other_outcome_measures_vector_383
0,1,1,False,False,False,False,False,True,False,False,...,-0.201059,0.218681,-0.244830,-0.037846,-0.113514,-0.144362,0.127571,0.065967,-0.032978,0.021158
1,1,1,False,False,False,False,False,True,False,False,...,0.130234,-0.190815,-0.050503,0.256153,0.615008,-0.006029,0.632454,0.035349,-0.244361,0.165219
2,1,1,False,False,False,False,False,True,False,False,...,0.130234,-0.190815,-0.050503,0.256153,0.615008,-0.006029,0.632454,0.035349,-0.244361,0.165219
3,1,1,False,False,False,False,False,True,False,False,...,0.130234,-0.190815,-0.050503,0.256153,0.615008,-0.006029,0.632454,0.035349,-0.244361,0.165219
4,1,1,False,False,False,False,False,True,False,False,...,0.130234,-0.190815,-0.050503,0.256153,0.615008,-0.006029,0.632454,0.035349,-0.244361,0.165219
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
678,1,1,False,False,True,False,False,False,False,False,...,0.130234,-0.190815,-0.050503,0.256153,0.615008,-0.006029,0.632454,0.035349,-0.244361,0.165219
679,1,1,False,False,True,False,False,False,False,False,...,0.130234,-0.190815,-0.050503,0.256153,0.615008,-0.006029,0.632454,0.035349,-0.244361,0.165219
680,1,1,False,False,False,False,False,True,False,False,...,0.130234,-0.190815,-0.050503,0.256153,0.615008,-0.006029,0.632454,0.035349,-0.244361,0.165219
681,1,1,False,False,False,False,False,True,False,False,...,0.130234,-0.190815,-0.050503,0.256153,0.615008,-0.006029,0.632454,0.035349,-0.244361,0.165219
682,1,1,False,False,True,False,False,False,False,False,...,0.130234,-0.190815,-0.050503,0.256153,0.615008,-0.006029,0.632454,0.035349,-0.244361,0.165219

In [11]:
predicted_probs = pd.DataFrame(mlp_classifier.predict_proba(X))

In [12]:
predicted_probs

            0         1
0    0.980058  0.019942
1    0.990243  0.009757
2    0.996775  0.003225
3    0.999559  0.000441
4    0.990810  0.009190
..        ...       ...
678  0.990856  0.009144
679  0.993189  0.006811
680  0.994481  0.005519
681  0.992693  0.007307
682  0.983574  0.016426

[683 rows x 2 columns]

In [19]:
result = pd.concat([predicted_probs.reset_index(drop=True), y.reset_index(drop=True)], axis=1)

In [20]:
result

            0         1  label
0    0.980058  0.019942      0
1    0.990243  0.009757      0
2    0.996775  0.003225      0
3    0.999559  0.000441      0
4    0.990810  0.009190      0
..        ...       ...    ...
678  0.990856  0.009144      0
679  0.993189  0.006811      0
680  0.994481  0.005519      0
681  0.992693  0.007307      0
682  0.983574  0.016426      0

[683 rows x 3 columns]

In [23]:
result[result['label']==False].sort_values(0, ascending=True)

            0         1  label
147  0.543059  0.456941      0
475  0.587908  0.412092      0
498  0.594856  0.405144      0
96   0.638642  0.361358      0
449  0.722214  0.277786      0
..        ...       ...    ...
307  0.999726  0.000274      0
218  0.999738  0.000262      0
439  0.999749  0.000251      0
364  0.999769  0.000231      0
472  0.999885  0.000115      0

[660 rows x 3 columns]